"""Seed chronic-related c_* master tables from downloaded official sources.

Sources:
- 33_chronic_typedisch.xls from hdata.moph.go.th standard code page.
- hcode_health_office.csv from hcode.moph.go.th public CSV download.
"""

import csv
import re
import urllib.parse
from pathlib import Path

import psycopg
import xlrd

HERE = Path(__file__).parent
ROOT = HERE.parent.parent


def load_env():
    env = {}
    for line in (ROOT / ".env.local").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        env[key.strip()] = value.strip()
    return env


def parse_db_url(url):
    parsed = urllib.parse.urlparse(url)
    return {
        "host": parsed.hostname,
        "port": parsed.port,
        "user": parsed.username,
        "password": urllib.parse.unquote(parsed.password or ""),
        "dbname": parsed.path.lstrip("/"),
    }


def clean_code(value, width=None):
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    # CSV exported by hcode wraps numeric text as Excel formulas: ="32045".
    match = re.fullmatch(r'="?([^"]+)"?', text)
    if match:
        text = match.group(1)
    if text.endswith(".0") and text[:-2].isdigit():
        text = text[:-2]
    return text.zfill(width) if width and text.isdigit() else text


def typedisch_rows():
    book = xlrd.open_workbook(str(HERE / "33_chronic_typedisch.xls"))
    sheet = book.sheet_by_index(0)
    rows = []
    for idx in range(2, sheet.nrows):
        code = clean_code(sheet.cell_value(idx, 0), 2)
        name = str(sheet.cell_value(idx, 1)).strip()
        if code and name:
            rows.append((code, name))
    return rows


def hospcode_rows():
    csv_path = HERE / "hcode_health_office.csv"
    with csv_path.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            code5 = clean_code(row.get("รหัส 5 หลัก"), 5)
            code9 = clean_code(row.get("รหัส 9 หลัก"), 9)
            hcode9 = clean_code(row.get("รหัส 9 หลักใหม่"))
            name = (row.get("ชื่อ") or "").strip()
            if not name or not (code5 or code9 or hcode9):
                continue
            yield (
                code5,
                code9,
                hcode9,
                name,
                (row.get("ประเภทองค์กร") or "").strip() or None,
                (row.get("ประเภทหน่วยบริการสุขภาพ") or "").strip() or None,
                (row.get("สังกัด") or "").strip() or None,
                (row.get("แผนก/กรม") or "").strip() or None,
                (row.get("ระดับโรงพยาบาล") or "").strip() or None,
                (row.get("สถานะการใช้งาน") or "").strip() or None,
                (row.get("เขตบริการ") or "").strip() or None,
                clean_code(row.get("รหัสจังหวัด"), 2),
                (row.get("จังหวัด") or "").strip() or None,
                clean_code(row.get("รหัสอำเภอ"), 4),
                (row.get("อำเภอ/เขต") or "").strip() or None,
                clean_code(row.get("รหัสตำบล"), 6),
                (row.get("ตำบล/แขวง") or "").strip() or None,
                (row.get("ที่อยู่") or "").strip() or None,
            )


DDL = """
create table if not exists public.c_chronic_typedisch (
  id bigint generated by default as identity primary key,
  code varchar(2) not null,
  name varchar(250) not null
);

create unique index if not exists c_chronic_typedisch_code_uq
  on public.c_chronic_typedisch (code);

create table if not exists public.c_hospcode (
  id bigint generated by default as identity primary key,
  code varchar(5),
  code9 varchar(9),
  hcode9 varchar(9),
  name text not null,
  organization_type text,
  health_office_type text,
  organization text,
  department text,
  hospital_level text,
  active_status text,
  health_zone text,
  province_code varchar(2),
  province text,
  district_code varchar(4),
  district text,
  subdistrict_code varchar(6),
  subdistrict text,
  address text
);

create unique index if not exists c_hospcode_code_uq
  on public.c_hospcode (code) where code is not null;
create unique index if not exists c_hospcode_code9_uq
  on public.c_hospcode (code9) where code9 is not null;
create unique index if not exists c_hospcode_hcode9_uq
  on public.c_hospcode (hcode9) where hcode9 is not null;
create index if not exists c_hospcode_name_idx on public.c_hospcode (name);
"""


def main():
    conn_info = parse_db_url(load_env()["DATABASE_URL"])
    with psycopg.connect(**conn_info, autocommit=False) as conn:
        with conn.cursor() as cur:
            cur.execute(DDL)

            typedisch = typedisch_rows()
            cur.executemany(
                """
                insert into public.c_chronic_typedisch (code, name)
                values (%s, %s)
                on conflict (code) do update set name = excluded.name
                """,
                typedisch,
            )

            cur.execute("truncate table public.c_hospcode restart identity")
            cur.executemany(
                """
                insert into public.c_hospcode (
                  code, code9, hcode9, name, organization_type, health_office_type,
                  organization, department, hospital_level, active_status, health_zone,
                  province_code, province, district_code, district, subdistrict_code,
                  subdistrict, address
                )
                values (
                  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                )
                on conflict do nothing
                """,
                list(hospcode_rows()),
            )
            cur.execute(
                """
                update public.c_hospcode
                set name = 'ไม่ทราบหน่วยบริการ',
                    active_status = 'ใช้ในแฟ้ม CHRONIC เมื่อไม่ทราบหน่วยบริการที่วินิจฉัยครั้งแรก'
                where code = '00000'
                """
            )
            cur.execute(
                """
                insert into public.c_hospcode (code, name, active_status)
                select
                  '00000',
                  'ไม่ทราบหน่วยบริการ',
                  'ใช้ในแฟ้ม CHRONIC เมื่อไม่ทราบหน่วยบริการที่วินิจฉัยครั้งแรก'
                where not exists (
                  select 1 from public.c_hospcode where code = '00000'
                )
                """
            )
        conn.commit()

    print(f"c_chronic_typedisch: {len(typedisch)} rows from 33_chronic_typedisch.xls")
    print("c_hospcode: imported from hcode_health_office.csv")


if __name__ == "__main__":
    main()
