begin;

create table if not exists public.c_chronic (
  id bigint generated by default as identity primary key,
  code varchar(20) not null,
  name varchar(250) not null
);

create unique index if not exists c_chronic_code_uq on public.c_chronic (code);

commit;
