begin;

alter table public.c_chronic
  add column if not exists is_chronic boolean not null default true;

create table if not exists public.c_chronic_typedisch (
  id bigint generated by default as identity primary key,
  code varchar(2) not null,
  name varchar(250) not null
);

create unique index if not exists c_chronic_typedisch_code_uq
  on public.c_chronic_typedisch (code);

insert into public.c_chronic_typedisch (code, name) values
  ('01', 'หาย'),
  ('02', 'ตาย'),
  ('03', 'ยังรักษาอยู่'),
  ('04', 'ไม่ทราบ'),
  ('05', 'รอจำหน่าย/เฝ้าระวัง'),
  ('06', 'ขาดการรักษาไม่มาติดต่ออีก'),
  ('07', 'ครบการรักษา'),
  ('08', 'โรคอยู่ในภาวะสงบ'),
  ('09', 'ปฏิเสธการรักษา'),
  ('10', 'ออกจากพื้นที่'),
  ('11', 'กลับเป็นซ้ำ')
on conflict (code) do update set
  name = excluded.name;

commit;
