-- Generated from MariaDB database temp structure.
-- Source: mariadb:10.6.23-ubi9, database temp.
-- Target: Supabase/Postgres database ehr, schema public.

begin;

create schema if not exists public;

create table if not exists public."tmp_exp_3093_accident" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "seq" varchar(16),
  "datetime_serv" varchar(14),
  "datetime_ae" varchar(14),
  "aetype" varchar(2),
  "aeplace" varchar(2),
  "typein_ae" varchar(1),
  "traffic" varchar(1),
  "vehicle" varchar(2),
  "alcohol" varchar(1),
  "nacrotic_drug" varchar(1),
  "belt" varchar(1),
  "helmet" varchar(1),
  "airway" varchar(1),
  "stopbleed" varchar(1),
  "splint" varchar(1),
  "fluid" varchar(1),
  "urgency" varchar(1),
  "coma_eye" varchar(1),
  "coma_speak" varchar(1),
  "coma_movement" varchar(1),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_address" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "addresstype" varchar(1),
  "house_id" varchar(11),
  "housetype" varchar(1),
  "roomno" varchar(10),
  "condo" varchar(75),
  "houseno" varchar(75),
  "soisub" varchar(200),
  "soimain" varchar(200),
  "road" varchar(200),
  "villaname" varchar(200),
  "village" varchar(2),
  "tambon" varchar(2),
  "ampur" varchar(2),
  "changwat" varchar(2),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_admission" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "seq" varchar(16),
  "an" varchar(9),
  "datetime_admit" varchar(14),
  "wardadmit" varchar(5),
  "instype" varchar(4),
  "typein" varchar(1),
  "referinhosp" varchar(9),
  "causein" varchar(1),
  "admitweight" varchar(5),
  "admitheight" varchar(3),
  "datetime_disch" varchar(14),
  "warddisch" varchar(5),
  "dischstatus" varchar(1),
  "dischtype" varchar(1),
  "referouthosp" varchar(9),
  "causeout" varchar(1),
  "cost" varchar(11),
  "price" varchar(11),
  "payprice" varchar(11),
  "actualpay" varchar(11),
  "provider" varchar(15),
  "d_update" varchar(14),
  "drg" varchar(5),
  "rw" varchar(11),
  "adjrw" varchar(11),
  "error" varchar(2),
  "warning" varchar(2),
  "actlos" varchar(4),
  "grouper_version" varchar(20),
  "cid" varchar(15),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_anc" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "gravida" varchar(2),
  "ancno" varchar(1),
  "ga" varchar(2),
  "ancresult" varchar(1),
  "ancplace" varchar(5),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "weight" varchar(10),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_appointment" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "an" varchar(9),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "clinic" varchar(5),
  "apdate" varchar(8),
  "aptype" varchar(3),
  "apdiag" varchar(6),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_card" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "instype_old" varchar(2),
  "instype_new" varchar(4),
  "insid" varchar(18),
  "startdate" varchar(8),
  "expiredate" varchar(8),
  "main" varchar(9),
  "sub" varchar(9),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_care_refer" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "referid" varchar(10),
  "referid_province" varchar(10),
  "caretype" varchar(1),
  "d_update" varchar(14),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_charge_ipd" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "an" varchar(9),
  "datetime_admit" varchar(14),
  "wardstay" varchar(5),
  "chargeitem" varchar(2),
  "chargelist" varchar(6),
  "quantity" varchar(11),
  "instype" varchar(4),
  "cost" varchar(11),
  "price" varchar(11),
  "payprice" varchar(11),
  "d_update" varchar(14),
  "cid" varchar(15),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_charge_opd" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "clinic" varchar(5),
  "chargeitem" varchar(2),
  "chargelist" varchar(6),
  "quantity" varchar(11),
  "instype" varchar(4),
  "cost" varchar(11),
  "price" varchar(11),
  "payprice" varchar(11),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_chronic" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "date_diag" varchar(8),
  "chronic" varchar(6),
  "hosp_dx" varchar(9),
  "hosp_rx" varchar(9),
  "date_disch" varchar(8),
  "typedisch" varchar(2),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_chronicfu" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "weight" varchar(5),
  "height" varchar(3),
  "waist_cm" varchar(3),
  "sbp" varchar(3),
  "dbp" varchar(3),
  "foot" varchar(1),
  "retina" varchar(1),
  "provider" varchar(15),
  "d_update" varchar(14),
  "chronicfuplace" varchar(5),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_clinical_refer" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "referid" varchar(10),
  "referid_province" varchar(10),
  "datetime_assess" varchar(14),
  "clinicalcode" varchar(6),
  "clinicalname" varchar(250),
  "clinicalvalue" varchar(6),
  "clinicalresult" varchar(250),
  "d_update" varchar(14),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_community_activity" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "vid" varchar(8),
  "date_start" varchar(8),
  "date_finish" varchar(8),
  "comactivity" varchar(7),
  "provider" varchar(15),
  "d_update" varchar(14),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_community_service" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "comservice" varchar(7),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_data_correct" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "tablename" varchar(30),
  "data_correct" varchar(250),
  "d_update" varchar(14),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_death" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "hospdeath" varchar(9),
  "an" varchar(9),
  "seq" varchar(16),
  "ddeath" varchar(8),
  "cdeath_a" varchar(6),
  "cdeath_b" varchar(6),
  "cdeath_c" varchar(6),
  "cdeath_d" varchar(6),
  "odisease" varchar(6),
  "cdeath" varchar(6),
  "pregdeath" varchar(1),
  "pdeath" varchar(1),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_dental" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "denttype" varchar(1),
  "servplace" varchar(1),
  "pteeth" varchar(2),
  "pcaries" varchar(2),
  "pfilling" varchar(2),
  "pextract" varchar(2),
  "dteeth" varchar(2),
  "dcaries" varchar(2),
  "dfilling" varchar(2),
  "dextract" varchar(2),
  "need_fluoride" varchar(1),
  "need_scaling" varchar(1),
  "need_sealant" varchar(2),
  "need_pfilling" varchar(2),
  "need_dfilling" varchar(2),
  "need_pextract" varchar(2),
  "need_dextract" varchar(2),
  "nprosthesis" varchar(1),
  "permanent_permanent" varchar(2),
  "permanent_prosthesis" varchar(2),
  "prosthesis_prosthesis" varchar(2),
  "gum" varchar(6),
  "schooltype" varchar(1),
  "class" varchar(1),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_diagnosis_ipd" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "an" varchar(9),
  "datetime_admit" varchar(14),
  "warddiag" varchar(5),
  "diagtype" varchar(1),
  "diagcode" varchar(6),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_diagnosis_opd" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "diagtype" varchar(1),
  "diagcode" varchar(7),
  "clinic" varchar(5),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_disability" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "disabid" varchar(13),
  "pid" varchar(13),
  "disabtype" varchar(1),
  "disabcause" varchar(1),
  "diagcode" varchar(6),
  "date_detect" varchar(8),
  "date_disab" varchar(8),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_drugallergy" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "daterecord" varchar(8),
  "drugallergy" varchar(24),
  "dname" varchar(200),
  "typedx" varchar(1),
  "alevel" varchar(1),
  "symptom" varchar(2),
  "informant" varchar(1),
  "informhosp" varchar(9),
  "d_update" varchar(14),
  "provider" varchar(15),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_drug_ipd" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "an" varchar(9),
  "datetime_admit" varchar(14),
  "wardstay" varchar(5),
  "typedrug" varchar(1),
  "didstd" varchar(24),
  "dname" varchar(250),
  "datestart" varchar(8),
  "datefinish" varchar(8),
  "amount" varchar(12),
  "unit" varchar(3),
  "unit_packing" varchar(20),
  "drugprice" varchar(11),
  "drugcost" varchar(11),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_drug_opd" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "clinic" varchar(5),
  "didstd" varchar(24),
  "dname" varchar(250),
  "amount" varchar(15),
  "unit" varchar(20),
  "unit_packing" varchar(20),
  "drugprice" varchar(15),
  "drugcost" varchar(15),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_drug_refer" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "referid" varchar(10),
  "referid_province" varchar(10),
  "datetime_dstart" varchar(14),
  "datetime_dfinish" varchar(14),
  "didstd" varchar(24),
  "dname" varchar(250),
  "ddescription" varchar(250),
  "d_update" varchar(14),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_epi" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "vaccinetype" varchar(10),
  "vaccineplace" varchar(9),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_fp" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "fptype" varchar(1),
  "fpplace" varchar(9),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_functional" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "functional_test" varchar(2),
  "testresult" varchar(3),
  "dependent" varchar(1),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_home" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "hid" varchar(14),
  "house_id" varchar(11),
  "housetype" varchar(1),
  "roomno" varchar(10),
  "condo" varchar(75),
  "house" varchar(75),
  "soisub" varchar(200),
  "soimain" varchar(200),
  "road" varchar(200),
  "villaname" varchar(200),
  "village" varchar(2),
  "tambon" varchar(2),
  "ampur" varchar(2),
  "changwat" varchar(2),
  "telephone" varchar(10),
  "latitude" varchar(10),
  "longitude" varchar(10),
  "nfamily" varchar(2),
  "locatype" varchar(1),
  "vhvid" varchar(15),
  "headid" varchar(15),
  "toilet" varchar(1),
  "water" varchar(1),
  "watertype" varchar(1),
  "garbage" varchar(1),
  "housing" varchar(1),
  "durability" varchar(1),
  "cleanliness" varchar(1),
  "ventilation" varchar(1),
  "light" varchar(1),
  "watertm" varchar(1),
  "mfood" varchar(1),
  "bcontrol" varchar(1),
  "acontrol" varchar(1),
  "chemical" varchar(1),
  "outdate" varchar(8),
  "d_update" varchar(14),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_icf" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "disabid" varchar(13),
  "pid" varchar(13),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "icf" varchar(6),
  "qualifier" varchar(1),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_investigation_refer" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "referid" varchar(10),
  "referid_province" varchar(10),
  "datetime_invest" varchar(14),
  "investcode" varchar(6),
  "investname" varchar(250),
  "datetime_report" varchar(14),
  "investvalue" varchar(6),
  "investresult" varchar(250),
  "d_update" varchar(14),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_labfu" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "labtest" varchar(7),
  "labresult" varchar(250),
  "d_update" varchar(14),
  "labplace" varchar(9),
  "cid" varchar(13),
  "provider" varchar(15),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_labor" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "gravida" varchar(2),
  "lmp" varchar(8),
  "edc" varchar(8),
  "bdate" varchar(8),
  "bresult" varchar(6),
  "bplace" varchar(1),
  "bhosp" varchar(9),
  "btype" varchar(1),
  "bdoctor" varchar(1),
  "lborn" varchar(1),
  "sborn" varchar(1),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_ncdscreen" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "servplace" varchar(1),
  "smoke" varchar(1),
  "alcohol" varchar(1),
  "dmfamily" varchar(1),
  "htfamily" varchar(1),
  "weight" varchar(5),
  "height" varchar(3),
  "waist_cm" varchar(3),
  "sbp_1" varchar(3),
  "dbp_1" varchar(3),
  "sbp_2" varchar(3),
  "dbp_2" varchar(3),
  "bslevel" varchar(6),
  "bstest" varchar(1),
  "screenplace" varchar(9),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_newborn" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "mpid" varchar(15),
  "gravida" varchar(2),
  "ga" varchar(2),
  "bdate" varchar(8),
  "btime" varchar(6),
  "bplace" varchar(1),
  "bhosp" varchar(9),
  "birthno" varchar(1),
  "btype" varchar(1),
  "bdoctor" varchar(1),
  "bweight" varchar(4),
  "asphyxia" varchar(2),
  "vitk" varchar(1),
  "tsh" varchar(1),
  "tshresult" varchar(5),
  "d_update" varchar(14),
  "cid" varchar(13),
  "length" varchar(5),
  "headcircum" varchar(5),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_newborncare" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "seq" varchar(16),
  "bdate" varchar(8),
  "bcare" varchar(8),
  "bcplace" varchar(9),
  "bcareresult" varchar(1),
  "food" varchar(1),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_nutrition" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "nutritionplace" varchar(5),
  "weight" varchar(5),
  "height" varchar(3),
  "headcircum" varchar(5),
  "childdevelop" varchar(1),
  "food" varchar(1),
  "bottle" varchar(1),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_person" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "cid" varchar(13),
  "pid" varchar(13),
  "hid" varchar(14),
  "prename" varchar(3),
  "name" varchar(50),
  "lname" varchar(50),
  "hn" varchar(9),
  "sex" varchar(1),
  "birth" varchar(8),
  "mstatus" varchar(1),
  "occupation_old" varchar(4),
  "occupation_new" varchar(4),
  "race" varchar(3),
  "nation" varchar(3),
  "religion" varchar(2),
  "education" varchar(2),
  "fstatus" varchar(1),
  "father" varchar(13),
  "mother" varchar(13),
  "couple" varchar(13),
  "vstatus" varchar(1),
  "movein" varchar(8),
  "discharge" varchar(1),
  "ddischarge" varchar(8),
  "abogroup" varchar(1),
  "rhgroup" varchar(2),
  "labor" varchar(2),
  "passport" varchar(8),
  "typearea" varchar(1),
  "d_update" varchar(14),
  "telephone" varchar(14),
  "mobile" varchar(14),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_policy" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "policy_id" varchar(3),
  "policy_year" varchar(4),
  "policy_data" varchar(250),
  "d_update" varchar(14),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_postnatal" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "seq" varchar(16),
  "gravida" varchar(2),
  "bdate" varchar(8),
  "ppcare" varchar(8),
  "ppplace" varchar(9),
  "ppresult" varchar(1),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_prenatal" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "gravida" varchar(2),
  "lmp" varchar(8),
  "edc" varchar(8),
  "vdrl_result" varchar(1),
  "hb_result" varchar(1),
  "hiv_result" varchar(1),
  "date_hct" varchar(8),
  "hct_result" varchar(2),
  "thalassemia" varchar(1),
  "d_update" varchar(14),
  "provider" varchar(15),
  "cid" varchar(13),
  "height" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_procedure_ipd" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "an" varchar(9),
  "datetime_admit" varchar(14),
  "wardstay" varchar(5),
  "procedcode" varchar(9),
  "timestart" varchar(14),
  "timefinish" varchar(14),
  "serviceprice" varchar(11),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_procedure_opd" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "clinic" varchar(5),
  "procedcode" varchar(9),
  "serviceprice" varchar(11),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_procedure_refer" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "referid" varchar(10),
  "referid_province" varchar(10),
  "timestart" varchar(14),
  "timefinish" varchar(14),
  "procedurename" varchar(250),
  "procedcode" varchar(7),
  "pdescription" varchar(250),
  "procedresult" varchar(250),
  "provider" varchar(250),
  "d_update" varchar(14),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_provider" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "provider" varchar(15),
  "registerno" varchar(15),
  "council" varchar(2),
  "cid" varchar(13),
  "prename" varchar(20),
  "name" varchar(50),
  "lname" varchar(50),
  "sex" varchar(1),
  "birth" varchar(8),
  "providertype" varchar(3),
  "startdate" varchar(8),
  "outdate" varchar(8),
  "movefrom" varchar(9),
  "moveto" varchar(9),
  "d_update" varchar(14),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_refer_history" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "referid" varchar(10),
  "referid_province" varchar(10),
  "pid" varchar(15),
  "seq" varchar(16),
  "an" varchar(9),
  "referid_origin" varchar(10),
  "hospcode_origin" varchar(9),
  "datetime_serv" varchar(14),
  "datetime_admit" varchar(14),
  "datetime_refer" varchar(14),
  "clinic_refer" varchar(5),
  "hosp_destination" varchar(9),
  "chiefcomp" varchar(250),
  "physicalexam" varchar(250),
  "diagfirst" varchar(250),
  "diaglast" varchar(250),
  "pstatus" varchar(250),
  "ptype" varchar(1),
  "emergency" varchar(1),
  "ptypedis" varchar(2),
  "causeout" varchar(1),
  "request" varchar(250),
  "provider" varchar(15),
  "d_update" varchar(14),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_refer_result" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "referid_source" varchar(10),
  "referid_province" varchar(10),
  "hosp_source" varchar(9),
  "refer_result" varchar(1),
  "datetime_in" varchar(14),
  "pid_in" varchar(15),
  "an_in" varchar(9),
  "reason" varchar(250),
  "d_update" varchar(14),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_rehabilitation" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "seq" varchar(16),
  "an" varchar(9),
  "date_admit" varchar(14),
  "date_serv" varchar(8),
  "date_start" varchar(8),
  "date_finish" varchar(8),
  "rehabcode" varchar(7),
  "at_device" varchar(10),
  "at_no" varchar(2),
  "rehabplace" varchar(9),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_service" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(15),
  "hn" varchar(15),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "time_serv" varchar(6),
  "location" varchar(1),
  "intime" varchar(1),
  "instype" varchar(4),
  "insid" varchar(18),
  "main" varchar(9),
  "typein" varchar(1),
  "referinhosp" varchar(9),
  "causein" varchar(1),
  "chiefcomp" varchar(250),
  "servplace" varchar(1),
  "btemp" varchar(10),
  "sbp" varchar(3),
  "dbp" varchar(3),
  "pr" varchar(3),
  "rr" varchar(3),
  "typeout" varchar(1),
  "referouthosp" varchar(9),
  "causeout" varchar(1),
  "cost" varchar(11),
  "price" varchar(11),
  "payprice" varchar(11),
  "actualpay" varchar(11),
  "d_update" varchar(14),
  "hsub" varchar(9),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_specialpp" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "servplace" varchar(1),
  "ppspecial" varchar(6),
  "ppsplace" varchar(9),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_surveillance" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "seq" varchar(16),
  "date_serv" varchar(8),
  "an" varchar(9),
  "datetime_admit" varchar(14),
  "syndrome" varchar(4),
  "diagcode" varchar(5),
  "code506" varchar(2),
  "diagcodelast" varchar(6),
  "code506last" varchar(2),
  "illdate" varchar(8),
  "illhouse" varchar(75),
  "illvillage" varchar(2),
  "illtambon" varchar(2),
  "illampur" varchar(2),
  "illchangwat" varchar(2),
  "latitude" varchar(10),
  "longitude" varchar(10),
  "ptstatus" varchar(1),
  "date_death" varchar(8),
  "complication" varchar(3),
  "organism" varchar(4),
  "provider" varchar(15),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_village" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "vid" varchar(8),
  "ntraditional" varchar(4),
  "nmonk" varchar(4),
  "nreligionleader" varchar(4),
  "nbroadcast" varchar(2),
  "nradio" varchar(2),
  "npchc" varchar(2),
  "nclinic" varchar(3),
  "ndrugstore" varchar(3),
  "nchildcenter" varchar(3),
  "npschool" varchar(2),
  "nsschool" varchar(2),
  "ntemple" varchar(2),
  "nreligiousplace" varchar(2),
  "nmarket" varchar(2),
  "nshop" varchar(3),
  "nfoodshop" varchar(3),
  "nstall" varchar(3),
  "nraintank" varchar(3),
  "nchickenfarm" varchar(3),
  "npigfarm" varchar(3),
  "wastewater" varchar(1),
  "garbage" varchar(1),
  "nfactory" varchar(3),
  "latitude" varchar(10),
  "longitude" varchar(10),
  "outdate" varchar(8),
  "numactually" varchar(2),
  "risktype" varchar(3),
  "numstateless" varchar(3),
  "nexerciseclub" varchar(3),
  "nolderlyclub" varchar(3),
  "ndisableclub" varchar(3),
  "nnumberoneclub" varchar(3),
  "d_update" varchar(14),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create table if not exists public."tmp_exp_3093_women" (
  "id" bigint generated by default as identity primary key,
  "hospcode" varchar(9),
  "pid" varchar(13),
  "fptype" varchar(1),
  "nofpcause" varchar(1),
  "totalson" varchar(2),
  "numberson" varchar(2),
  "abortion" varchar(2),
  "stillbirth" varchar(2),
  "d_update" varchar(14),
  "cid" varchar(13),
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "created_by" text,
  "updated_by" text
);

create index if not exists "tmp_exp_3093_accident_ix_cid" on public."tmp_exp_3093_accident" ("cid");
create index if not exists "tmp_exp_3093_accident_ix_pid" on public."tmp_exp_3093_accident" ("pid");
create index if not exists "tmp_exp_3093_accident_ix_seq" on public."tmp_exp_3093_accident" ("seq");
create index if not exists "tmp_exp_3093_address_ix_cid" on public."tmp_exp_3093_address" ("cid");
create index if not exists "tmp_exp_3093_address_ix_pid" on public."tmp_exp_3093_address" ("pid");
create index if not exists "tmp_exp_3093_admission_ix_cid" on public."tmp_exp_3093_admission" ("cid");
create index if not exists "tmp_exp_3093_admission_ix_pid" on public."tmp_exp_3093_admission" ("pid");
create index if not exists "tmp_exp_3093_admission_ix_seq" on public."tmp_exp_3093_admission" ("seq");
create index if not exists "tmp_exp_3093_anc_ix_cid" on public."tmp_exp_3093_anc" ("cid");
create index if not exists "tmp_exp_3093_anc_ix_pid" on public."tmp_exp_3093_anc" ("pid");
create index if not exists "tmp_exp_3093_anc_ix_seq" on public."tmp_exp_3093_anc" ("seq");
create index if not exists "tmp_exp_3093_appointment_ix_cid" on public."tmp_exp_3093_appointment" ("cid");
create index if not exists "tmp_exp_3093_appointment_ix_pid" on public."tmp_exp_3093_appointment" ("pid");
create index if not exists "tmp_exp_3093_appointment_ix_seq" on public."tmp_exp_3093_appointment" ("seq");
create index if not exists "tmp_exp_3093_card_ix_cid" on public."tmp_exp_3093_card" ("cid");
create index if not exists "tmp_exp_3093_card_ix_pid" on public."tmp_exp_3093_card" ("pid");
create index if not exists "tmp_exp_3093_charge_ipd_ix_cid" on public."tmp_exp_3093_charge_ipd" ("cid");
create index if not exists "tmp_exp_3093_charge_ipd_ix_pid" on public."tmp_exp_3093_charge_ipd" ("pid");
create index if not exists "tmp_exp_3093_charge_opd_ix_cid" on public."tmp_exp_3093_charge_opd" ("cid");
create index if not exists "tmp_exp_3093_charge_opd_ix_pid" on public."tmp_exp_3093_charge_opd" ("pid");
create index if not exists "tmp_exp_3093_charge_opd_ix_seq" on public."tmp_exp_3093_charge_opd" ("seq");
create index if not exists "tmp_exp_3093_chronic_ix_cid" on public."tmp_exp_3093_chronic" ("cid");
create index if not exists "tmp_exp_3093_chronic_ix_pid" on public."tmp_exp_3093_chronic" ("pid");
create index if not exists "tmp_exp_3093_chronicfu_ix_cid" on public."tmp_exp_3093_chronicfu" ("cid");
create index if not exists "tmp_exp_3093_chronicfu_ix_pid" on public."tmp_exp_3093_chronicfu" ("pid");
create index if not exists "tmp_exp_3093_chronicfu_ix_seq" on public."tmp_exp_3093_chronicfu" ("seq");
create index if not exists "tmp_exp_3093_community_service_ix_cid" on public."tmp_exp_3093_community_service" ("cid");
create index if not exists "tmp_exp_3093_community_service_ix_pid" on public."tmp_exp_3093_community_service" ("pid");
create index if not exists "tmp_exp_3093_community_service_ix_seq" on public."tmp_exp_3093_community_service" ("seq");
create index if not exists "tmp_exp_3093_death_ix_cid" on public."tmp_exp_3093_death" ("cid");
create index if not exists "tmp_exp_3093_death_ix_pid" on public."tmp_exp_3093_death" ("pid");
create index if not exists "tmp_exp_3093_death_ix_seq" on public."tmp_exp_3093_death" ("seq");
create index if not exists "tmp_exp_3093_dental_ix_cid" on public."tmp_exp_3093_dental" ("cid");
create index if not exists "tmp_exp_3093_dental_ix_pid" on public."tmp_exp_3093_dental" ("pid");
create index if not exists "tmp_exp_3093_dental_ix_seq" on public."tmp_exp_3093_dental" ("seq");
create index if not exists "tmp_exp_3093_diagnosis_ipd_ix_cid" on public."tmp_exp_3093_diagnosis_ipd" ("cid");
create index if not exists "tmp_exp_3093_diagnosis_ipd_ix_pid" on public."tmp_exp_3093_diagnosis_ipd" ("pid");
create index if not exists "tmp_exp_3093_diagnosis_opd_ix_cid" on public."tmp_exp_3093_diagnosis_opd" ("cid");
create index if not exists "tmp_exp_3093_diagnosis_opd_ix_pid" on public."tmp_exp_3093_diagnosis_opd" ("pid");
create index if not exists "tmp_exp_3093_diagnosis_opd_ix_seq" on public."tmp_exp_3093_diagnosis_opd" ("seq");
create index if not exists "tmp_exp_3093_disability_ix_cid" on public."tmp_exp_3093_disability" ("cid");
create index if not exists "tmp_exp_3093_disability_ix_pid" on public."tmp_exp_3093_disability" ("pid");
create index if not exists "tmp_exp_3093_drugallergy_ix_cid" on public."tmp_exp_3093_drugallergy" ("cid");
create index if not exists "tmp_exp_3093_drugallergy_ix_pid" on public."tmp_exp_3093_drugallergy" ("pid");
create index if not exists "tmp_exp_3093_drug_ipd_ix_cid" on public."tmp_exp_3093_drug_ipd" ("cid");
create index if not exists "tmp_exp_3093_drug_ipd_ix_pid" on public."tmp_exp_3093_drug_ipd" ("pid");
create index if not exists "tmp_exp_3093_drug_opd_ix_cid" on public."tmp_exp_3093_drug_opd" ("cid");
create index if not exists "tmp_exp_3093_drug_opd_ix_pid" on public."tmp_exp_3093_drug_opd" ("pid");
create index if not exists "tmp_exp_3093_drug_opd_ix_seq" on public."tmp_exp_3093_drug_opd" ("seq");
create index if not exists "tmp_exp_3093_epi_ix_cid" on public."tmp_exp_3093_epi" ("cid");
create index if not exists "tmp_exp_3093_epi_ix_pid" on public."tmp_exp_3093_epi" ("pid");
create index if not exists "tmp_exp_3093_epi_ix_seq" on public."tmp_exp_3093_epi" ("seq");
create index if not exists "tmp_exp_3093_fp_ix_cid" on public."tmp_exp_3093_fp" ("cid");
create index if not exists "tmp_exp_3093_fp_ix_pid" on public."tmp_exp_3093_fp" ("pid");
create index if not exists "tmp_exp_3093_fp_ix_seq" on public."tmp_exp_3093_fp" ("seq");
create index if not exists "tmp_exp_3093_functional_ix_cid" on public."tmp_exp_3093_functional" ("cid");
create index if not exists "tmp_exp_3093_functional_ix_pid" on public."tmp_exp_3093_functional" ("pid");
create index if not exists "tmp_exp_3093_functional_ix_seq" on public."tmp_exp_3093_functional" ("seq");
create index if not exists "tmp_exp_3093_icf_ix_cid" on public."tmp_exp_3093_icf" ("cid");
create index if not exists "tmp_exp_3093_icf_ix_pid" on public."tmp_exp_3093_icf" ("pid");
create index if not exists "tmp_exp_3093_icf_ix_seq" on public."tmp_exp_3093_icf" ("seq");
create index if not exists "tmp_exp_3093_labfu_ix_cid" on public."tmp_exp_3093_labfu" ("cid");
create index if not exists "tmp_exp_3093_labfu_ix_pid" on public."tmp_exp_3093_labfu" ("pid");
create index if not exists "tmp_exp_3093_labfu_ix_seq" on public."tmp_exp_3093_labfu" ("seq");
create index if not exists "tmp_exp_3093_labor_ix_cid" on public."tmp_exp_3093_labor" ("cid");
create index if not exists "tmp_exp_3093_labor_ix_pid" on public."tmp_exp_3093_labor" ("pid");
create index if not exists "tmp_exp_3093_ncdscreen_ix_cid" on public."tmp_exp_3093_ncdscreen" ("cid");
create index if not exists "tmp_exp_3093_ncdscreen_ix_pid" on public."tmp_exp_3093_ncdscreen" ("pid");
create index if not exists "tmp_exp_3093_ncdscreen_ix_seq" on public."tmp_exp_3093_ncdscreen" ("seq");
create index if not exists "tmp_exp_3093_newborn_ix_cid" on public."tmp_exp_3093_newborn" ("cid");
create index if not exists "tmp_exp_3093_newborn_ix_pid" on public."tmp_exp_3093_newborn" ("pid");
create index if not exists "tmp_exp_3093_newborncare_ix_cid" on public."tmp_exp_3093_newborncare" ("cid");
create index if not exists "tmp_exp_3093_newborncare_ix_pid" on public."tmp_exp_3093_newborncare" ("pid");
create index if not exists "tmp_exp_3093_newborncare_ix_seq" on public."tmp_exp_3093_newborncare" ("seq");
create index if not exists "tmp_exp_3093_nutrition_ix_cid" on public."tmp_exp_3093_nutrition" ("cid");
create index if not exists "tmp_exp_3093_nutrition_ix_pid" on public."tmp_exp_3093_nutrition" ("pid");
create index if not exists "tmp_exp_3093_nutrition_ix_seq" on public."tmp_exp_3093_nutrition" ("seq");
create index if not exists "tmp_exp_3093_person_ix_cid" on public."tmp_exp_3093_person" ("cid");
create unique index if not exists "tmp_exp_3093_person_ix_pid" on public."tmp_exp_3093_person" ("pid");
create index if not exists "tmp_exp_3093_postnatal_ix_cid" on public."tmp_exp_3093_postnatal" ("cid");
create index if not exists "tmp_exp_3093_postnatal_ix_pid" on public."tmp_exp_3093_postnatal" ("pid");
create index if not exists "tmp_exp_3093_postnatal_ix_seq" on public."tmp_exp_3093_postnatal" ("seq");
create index if not exists "tmp_exp_3093_prenatal_ix_cid" on public."tmp_exp_3093_prenatal" ("cid");
create index if not exists "tmp_exp_3093_prenatal_ix_pid" on public."tmp_exp_3093_prenatal" ("pid");
create index if not exists "tmp_exp_3093_procedure_ipd_ix_cid" on public."tmp_exp_3093_procedure_ipd" ("cid");
create index if not exists "tmp_exp_3093_procedure_ipd_ix_pid" on public."tmp_exp_3093_procedure_ipd" ("pid");
create index if not exists "tmp_exp_3093_procedure_opd_ix_cid" on public."tmp_exp_3093_procedure_opd" ("cid");
create index if not exists "tmp_exp_3093_procedure_opd_ix_pid" on public."tmp_exp_3093_procedure_opd" ("pid");
create index if not exists "tmp_exp_3093_procedure_opd_ix_seq" on public."tmp_exp_3093_procedure_opd" ("seq");
create index if not exists "tmp_exp_3093_provider_ix_cid" on public."tmp_exp_3093_provider" ("cid");
create index if not exists "tmp_exp_3093_refer_history_ix_pid" on public."tmp_exp_3093_refer_history" ("pid");
create index if not exists "tmp_exp_3093_refer_history_ix_seq" on public."tmp_exp_3093_refer_history" ("seq");
create index if not exists "tmp_exp_3093_rehabilitation_ix_cid" on public."tmp_exp_3093_rehabilitation" ("cid");
create index if not exists "tmp_exp_3093_rehabilitation_ix_pid" on public."tmp_exp_3093_rehabilitation" ("pid");
create index if not exists "tmp_exp_3093_rehabilitation_ix_seq" on public."tmp_exp_3093_rehabilitation" ("seq");
create index if not exists "tmp_exp_3093_service_ix_cid" on public."tmp_exp_3093_service" ("cid");
create index if not exists "tmp_exp_3093_service_ix_pid" on public."tmp_exp_3093_service" ("pid");
create index if not exists "tmp_exp_3093_service_ix_seq" on public."tmp_exp_3093_service" ("seq");
create index if not exists "tmp_exp_3093_specialpp_ix_cid" on public."tmp_exp_3093_specialpp" ("cid");
create index if not exists "tmp_exp_3093_specialpp_ix_pid" on public."tmp_exp_3093_specialpp" ("pid");
create index if not exists "tmp_exp_3093_specialpp_ix_seq" on public."tmp_exp_3093_specialpp" ("seq");
create index if not exists "tmp_exp_3093_surveillance_ix_cid" on public."tmp_exp_3093_surveillance" ("cid");
create index if not exists "tmp_exp_3093_surveillance_ix_pid" on public."tmp_exp_3093_surveillance" ("pid");
create index if not exists "tmp_exp_3093_surveillance_ix_seq" on public."tmp_exp_3093_surveillance" ("seq");
create index if not exists "tmp_exp_3093_women_ix_cid" on public."tmp_exp_3093_women" ("cid");
create index if not exists "tmp_exp_3093_women_ix_pid" on public."tmp_exp_3093_women" ("pid");

commit;

