do $$
declare
  item record;
begin
  for item in
    select table_name
    from information_schema.tables
    where table_schema = 'public'
      and table_type = 'BASE TABLE'
    order by table_name
  loop
    if not exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and table_name = item.table_name
        and column_name = 'id'
    ) then
      execute format(
        'alter table public.%I add column id bigint generated by default as identity',
        item.table_name
      );

      execute format(
        'alter table public.%I add constraint %I primary key (id)',
        item.table_name,
        item.table_name || '_pkey'
      );
    end if;
  end loop;
end
$$;
